CONFIG_MCUBOOT_SERIAL=y
CONFIG_BOOT_SERIAL_UART=y
CONFIG_BOOT_SERIAL_ENTRANCE_GPIO=y
CONFIG_BOOT_SERIAL_DETECT_DELAY=50
CONFIG_FPROTECT=y
CONFIG_UART_CONSOLE=n
CONFIG_BOOT_MAX_IMG_SECTORS=2048
CONFIG_BOOT_SERIAL_NO_APPLICATION=y
