/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#include <app-common/zap-generated/callback.h>
#include <app-common/zap-generated/ids/Clusters.h>
#include <lib/support/Span.h>
#include <protocols/interaction_model/Constants.h>

using namespace chip;

// Cluster Init Functions
void emberAfClusterInitCallback(EndpointId endpoint, ClusterId clusterId) {
  switch (clusterId) {
  case app::Clusters::AccessControl::Id:
    emberAfAccessControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::AdministratorCommissioning::Id:
    emberAfAdministratorCommissioningClusterInitCallback(endpoint);
    break;
  case app::Clusters::AirQuality::Id:
    emberAfAirQualityClusterInitCallback(endpoint);
    break;
  case app::Clusters::BasicInformation::Id:
    emberAfBasicInformationClusterInitCallback(endpoint);
    break;
  case app::Clusters::BooleanState::Id:
    emberAfBooleanStateClusterInitCallback(endpoint);
    break;
  case app::Clusters::Chime::Id:
    emberAfChimeClusterInitCallback(endpoint);
    break;
  case app::Clusters::ColorControl::Id:
    emberAfColorControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::Descriptor::Id:
    emberAfDescriptorClusterInitCallback(endpoint);
    break;
  case app::Clusters::DeviceEnergyManagement::Id:
    emberAfDeviceEnergyManagementClusterInitCallback(endpoint);
    break;
  case app::Clusters::DeviceEnergyManagementMode::Id:
    emberAfDeviceEnergyManagementModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::DiagnosticLogs::Id:
    emberAfDiagnosticLogsClusterInitCallback(endpoint);
    break;
  case app::Clusters::DoorLock::Id:
    emberAfDoorLockClusterInitCallback(endpoint);
    break;
  case app::Clusters::ElectricalEnergyMeasurement::Id:
    emberAfElectricalEnergyMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::ElectricalPowerMeasurement::Id:
    emberAfElectricalPowerMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::FanControl::Id:
    emberAfFanControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::FlowMeasurement::Id:
    emberAfFlowMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::GeneralCommissioning::Id:
    emberAfGeneralCommissioningClusterInitCallback(endpoint);
    break;
  case app::Clusters::GeneralDiagnostics::Id:
    emberAfGeneralDiagnosticsClusterInitCallback(endpoint);
    break;
  case app::Clusters::GroupKeyManagement::Id:
    emberAfGroupKeyManagementClusterInitCallback(endpoint);
    break;
  case app::Clusters::Groups::Id:
    emberAfGroupsClusterInitCallback(endpoint);
    break;
  case app::Clusters::Identify::Id:
    emberAfIdentifyClusterInitCallback(endpoint);
    break;
  case app::Clusters::IlluminanceMeasurement::Id:
    emberAfIlluminanceMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::LevelControl::Id:
    emberAfLevelControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::MeterIdentification::Id:
    emberAfMeterIdentificationClusterInitCallback(endpoint);
    break;
  case app::Clusters::MicrowaveOvenControl::Id:
    emberAfMicrowaveOvenControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::MicrowaveOvenMode::Id:
    emberAfMicrowaveOvenModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::ModeSelect::Id:
    emberAfModeSelectClusterInitCallback(endpoint);
    break;
  case app::Clusters::NetworkCommissioning::Id:
    emberAfNetworkCommissioningClusterInitCallback(endpoint);
    break;
  case app::Clusters::OtaSoftwareUpdateProvider::Id:
    emberAfOtaSoftwareUpdateProviderClusterInitCallback(endpoint);
    break;
  case app::Clusters::OtaSoftwareUpdateRequestor::Id:
    emberAfOtaSoftwareUpdateRequestorClusterInitCallback(endpoint);
    break;
  case app::Clusters::OccupancySensing::Id:
    emberAfOccupancySensingClusterInitCallback(endpoint);
    break;
  case app::Clusters::OnOff::Id:
    emberAfOnOffClusterInitCallback(endpoint);
    break;
  case app::Clusters::OperationalCredentials::Id:
    emberAfOperationalCredentialsClusterInitCallback(endpoint);
    break;
  case app::Clusters::OperationalState::Id:
    emberAfOperationalStateClusterInitCallback(endpoint);
    break;
  case app::Clusters::OvenCavityOperationalState::Id:
    emberAfOvenCavityOperationalStateClusterInitCallback(endpoint);
    break;
  case app::Clusters::OvenMode::Id:
    emberAfOvenModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::PowerSource::Id:
    emberAfPowerSourceClusterInitCallback(endpoint);
    break;
  case app::Clusters::PowerTopology::Id:
    emberAfPowerTopologyClusterInitCallback(endpoint);
    break;
  case app::Clusters::PressureMeasurement::Id:
    emberAfPressureMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::PumpConfigurationAndControl::Id:
    emberAfPumpConfigurationAndControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::RvcCleanMode::Id:
    emberAfRvcCleanModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::RvcOperationalState::Id:
    emberAfRvcOperationalStateClusterInitCallback(endpoint);
    break;
  case app::Clusters::RvcRunMode::Id:
    emberAfRvcRunModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::RefrigeratorAlarm::Id:
    emberAfRefrigeratorAlarmClusterInitCallback(endpoint);
    break;
  case app::Clusters::RefrigeratorAndTemperatureControlledCabinetMode::Id:
    emberAfRefrigeratorAndTemperatureControlledCabinetModeClusterInitCallback(
        endpoint);
    break;
  case app::Clusters::RelativeHumidityMeasurement::Id:
    emberAfRelativeHumidityMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::SmokeCoAlarm::Id:
    emberAfSmokeCoAlarmClusterInitCallback(endpoint);
    break;
  case app::Clusters::SoftwareDiagnostics::Id:
    emberAfSoftwareDiagnosticsClusterInitCallback(endpoint);
    break;
  case app::Clusters::Switch::Id:
    emberAfSwitchClusterInitCallback(endpoint);
    break;
  case app::Clusters::TemperatureControl::Id:
    emberAfTemperatureControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::TemperatureMeasurement::Id:
    emberAfTemperatureMeasurementClusterInitCallback(endpoint);
    break;
  case app::Clusters::Thermostat::Id:
    emberAfThermostatClusterInitCallback(endpoint);
    break;
  case app::Clusters::ThreadNetworkDiagnostics::Id:
    emberAfThreadNetworkDiagnosticsClusterInitCallback(endpoint);
    break;
  case app::Clusters::ValveConfigurationAndControl::Id:
    emberAfValveConfigurationAndControlClusterInitCallback(endpoint);
    break;
  case app::Clusters::WaterHeaterManagement::Id:
    emberAfWaterHeaterManagementClusterInitCallback(endpoint);
    break;
  case app::Clusters::WaterHeaterMode::Id:
    emberAfWaterHeaterModeClusterInitCallback(endpoint);
    break;
  case app::Clusters::WiFiNetworkDiagnostics::Id:
    emberAfWiFiNetworkDiagnosticsClusterInitCallback(endpoint);
    break;
  case app::Clusters::WindowCovering::Id:
    emberAfWindowCoveringClusterInitCallback(endpoint);
    break;
  default:
    // Unrecognized cluster ID
    break;
  }
}

void __attribute__((weak))
emberAfAccessControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfAdministratorCommissioningClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfAirQualityClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfBasicInformationClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfBooleanStateClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfChimeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfColorControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfDescriptorClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfDeviceEnergyManagementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfDeviceEnergyManagementModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfDiagnosticLogsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfDoorLockClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfElectricalEnergyMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfElectricalPowerMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfFanControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfFlowMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfGeneralCommissioningClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfGeneralDiagnosticsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfGroupKeyManagementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfGroupsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfIdentifyClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfIlluminanceMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfLevelControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfMeterIdentificationClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfMicrowaveOvenControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfMicrowaveOvenModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfModeSelectClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfNetworkCommissioningClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOtaSoftwareUpdateProviderClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOtaSoftwareUpdateRequestorClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOccupancySensingClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOnOffClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOperationalCredentialsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOperationalStateClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOvenCavityOperationalStateClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfOvenModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfPowerSourceClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfPowerTopologyClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfPressureMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfPumpConfigurationAndControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRvcCleanModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRvcOperationalStateClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRvcRunModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRefrigeratorAlarmClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRefrigeratorAndTemperatureControlledCabinetModeClusterInitCallback(
    EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfRelativeHumidityMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfSmokeCoAlarmClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfSoftwareDiagnosticsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfSwitchClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfTemperatureControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfTemperatureMeasurementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfThermostatClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfThreadNetworkDiagnosticsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfValveConfigurationAndControlClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfWaterHeaterManagementClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfWaterHeaterModeClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfWiFiNetworkDiagnosticsClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
void __attribute__((weak))
emberAfWindowCoveringClusterInitCallback(EndpointId endpoint) {
  // To prevent warning
  (void)endpoint;
}
