/*
 *
 *    Copyright (c) 2022 Project CHIP Authors
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

// THIS FILE IS GENERATED BY ZAP

#pragma once

void MatterIdentifyPluginServerInitCallback();
void MatterGroupsPluginServerInitCallback();
void MatterOnOffPluginServerInitCallback();
void MatterLevelControlPluginServerInitCallback();
void MatterDescriptorPluginServerInitCallback();
void MatterAccessControlPluginServerInitCallback();
void MatterBasicInformationPluginServerInitCallback();
void MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();
void MatterPowerSourcePluginServerInitCallback();
void MatterGeneralCommissioningPluginServerInitCallback();
void MatterNetworkCommissioningPluginServerInitCallback();
void MatterDiagnosticLogsPluginServerInitCallback();
void MatterGeneralDiagnosticsPluginServerInitCallback();
void MatterSoftwareDiagnosticsPluginServerInitCallback();
void MatterThreadNetworkDiagnosticsPluginServerInitCallback();
void MatterWiFiNetworkDiagnosticsPluginServerInitCallback();
void MatterSwitchPluginServerInitCallback();
void MatterAdministratorCommissioningPluginServerInitCallback();
void MatterOperationalCredentialsPluginServerInitCallback();
void MatterGroupKeyManagementPluginServerInitCallback();
void MatterBooleanStatePluginServerInitCallback();
void MatterOvenCavityOperationalStatePluginServerInitCallback();
void MatterOvenModePluginServerInitCallback();
void MatterModeSelectPluginServerInitCallback();
void MatterRefrigeratorAndTemperatureControlledCabinetModePluginServerInitCallback();
void MatterRvcRunModePluginServerInitCallback();
void MatterRvcCleanModePluginServerInitCallback();
void MatterTemperatureControlPluginServerInitCallback();
void MatterRefrigeratorAlarmPluginServerInitCallback();
void MatterAirQualityPluginServerInitCallback();
void MatterSmokeCoAlarmPluginServerInitCallback();
void MatterMicrowaveOvenModePluginServerInitCallback();
void MatterMicrowaveOvenControlPluginServerInitCallback();
void MatterOperationalStatePluginServerInitCallback();
void MatterRvcOperationalStatePluginServerInitCallback();
void MatterValveConfigurationAndControlPluginServerInitCallback();
void MatterElectricalPowerMeasurementPluginServerInitCallback();
void MatterElectricalEnergyMeasurementPluginServerInitCallback();
void MatterWaterHeaterManagementPluginServerInitCallback();
void MatterDeviceEnergyManagementPluginServerInitCallback();
void MatterEnergyEvsePluginServerInitCallback();
void MatterPowerTopologyPluginServerInitCallback();
void MatterEnergyEvseModePluginServerInitCallback();
void MatterWaterHeaterModePluginServerInitCallback();
void MatterDeviceEnergyManagementModePluginServerInitCallback();
void MatterDoorLockPluginServerInitCallback();
void MatterWindowCoveringPluginServerInitCallback();
void MatterPumpConfigurationAndControlPluginServerInitCallback();
void MatterThermostatPluginServerInitCallback();
void MatterFanControlPluginServerInitCallback();
void MatterColorControlPluginServerInitCallback();
void MatterIlluminanceMeasurementPluginServerInitCallback();
void MatterTemperatureMeasurementPluginServerInitCallback();
void MatterPressureMeasurementPluginServerInitCallback();
void MatterFlowMeasurementPluginServerInitCallback();
void MatterRelativeHumidityMeasurementPluginServerInitCallback();
void MatterOccupancySensingPluginServerInitCallback();
void MatterChimePluginServerInitCallback();
void MatterMeterIdentificationPluginServerInitCallback();

#define MATTER_PLUGINS_INIT                                                        \
  MatterIdentifyPluginServerInitCallback();                                        \
  MatterGroupsPluginServerInitCallback();                                          \
  MatterOnOffPluginServerInitCallback();                                           \
  MatterLevelControlPluginServerInitCallback();                                    \
  MatterDescriptorPluginServerInitCallback();                                      \
  MatterAccessControlPluginServerInitCallback();                                   \
  MatterBasicInformationPluginServerInitCallback();                                \
  MatterOtaSoftwareUpdateRequestorPluginServerInitCallback();                      \
  MatterPowerSourcePluginServerInitCallback();                                     \
  MatterGeneralCommissioningPluginServerInitCallback();                            \
  MatterNetworkCommissioningPluginServerInitCallback();                            \
  MatterDiagnosticLogsPluginServerInitCallback();                                  \
  MatterGeneralDiagnosticsPluginServerInitCallback();                              \
  MatterSoftwareDiagnosticsPluginServerInitCallback();                             \
  MatterThreadNetworkDiagnosticsPluginServerInitCallback();                        \
  MatterWiFiNetworkDiagnosticsPluginServerInitCallback();                          \
  MatterSwitchPluginServerInitCallback();                                          \
  MatterAdministratorCommissioningPluginServerInitCallback();                      \
  MatterOperationalCredentialsPluginServerInitCallback();                          \
  MatterGroupKeyManagementPluginServerInitCallback();                              \
  MatterBooleanStatePluginServerInitCallback();                                    \
  MatterOvenCavityOperationalStatePluginServerInitCallback();                      \
  MatterOvenModePluginServerInitCallback();                                        \
  MatterModeSelectPluginServerInitCallback();                                      \
  MatterRefrigeratorAndTemperatureControlledCabinetModePluginServerInitCallback(); \
  MatterRvcRunModePluginServerInitCallback();                                      \
  MatterRvcCleanModePluginServerInitCallback();                                    \
  MatterTemperatureControlPluginServerInitCallback();                              \
  MatterRefrigeratorAlarmPluginServerInitCallback();                               \
  MatterAirQualityPluginServerInitCallback();                                      \
  MatterSmokeCoAlarmPluginServerInitCallback();                                    \
  MatterMicrowaveOvenModePluginServerInitCallback();                               \
  MatterMicrowaveOvenControlPluginServerInitCallback();                            \
  MatterOperationalStatePluginServerInitCallback();                                \
  MatterRvcOperationalStatePluginServerInitCallback();                             \
  MatterValveConfigurationAndControlPluginServerInitCallback();                    \
  MatterElectricalPowerMeasurementPluginServerInitCallback();                      \
  MatterElectricalEnergyMeasurementPluginServerInitCallback();                     \
  MatterWaterHeaterManagementPluginServerInitCallback();                           \
  MatterDeviceEnergyManagementPluginServerInitCallback();                          \
  MatterEnergyEvsePluginServerInitCallback();                                      \
  MatterPowerTopologyPluginServerInitCallback();                                   \
  MatterEnergyEvseModePluginServerInitCallback();                                  \
  MatterWaterHeaterModePluginServerInitCallback();                                 \
  MatterDeviceEnergyManagementModePluginServerInitCallback();                      \
  MatterDoorLockPluginServerInitCallback();                                        \
  MatterWindowCoveringPluginServerInitCallback();                                  \
  MatterPumpConfigurationAndControlPluginServerInitCallback();                     \
  MatterThermostatPluginServerInitCallback();                                      \
  MatterFanControlPluginServerInitCallback();                                      \
  MatterColorControlPluginServerInitCallback();                                    \
  MatterIlluminanceMeasurementPluginServerInitCallback();                          \
  MatterTemperatureMeasurementPluginServerInitCallback();                          \
  MatterPressureMeasurementPluginServerInitCallback();                             \
  MatterFlowMeasurementPluginServerInitCallback();                                 \
  MatterRelativeHumidityMeasurementPluginServerInitCallback();                     \
  MatterOccupancySensingPluginServerInitCallback();                                \
  MatterChimePluginServerInitCallback();                                           \
  MatterMeterIdentificationPluginServerInitCallback();
